name = "iupiew/gift-card"
version = "0.0.0"
compiler = "v1.0.31-alpha"
plutus = "v2"
license = "Apache-2.0"
description = "Aiken contracts for project 'iupiew/gift-card'"

[repository]
user = "iupiew"
project = "gift-card"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
